server.port=8081
application.name=springai-deepseek4j-gchain4j

# H2数据库配置

# PostgreSQL数据库配置
spring.datasource.url=jdbc:postgresql://localhost:5432/dify
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=difyai123456

# JPA配置
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=uuid
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

#logging.level.root=DEBUG
deepseek.connect-timeout=300
deepseek.read-timeout=600
deepseek.call-timeout=600

#remote deepseek_server invoke
deepseek.base_url=https://api.deepseek.com/v1
deepseek.api_key=your api key
deepseek.model=deepseek-chat

langchain4j.openai.chat-model.api-key=your api key
langchain4j.openai.chat-model.model-name=deepseek-chat
langchain4j.openai.chat-model.base-url=https://api.deepseek.com/v1
