server.port=8081
application.name=springai-deepseek4j-gchain4j

# H2数据库配置

# PostgreSQL数据库配置
spring.datasource.url=jdbc:postgresql://localhost:5433/dify
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=difyai123456

# JPA配置
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=uuid
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

#logging.level.root=DEBUG
logging.level.org.springframework.ai.chat.client=DEBUG
spring.ai.alibaba.toolcalling.weather.enabled=true
spring.ai.alibaba.toolcalling.weather.api-key=ed64d1b67a814fb5a5d93754251004

# 添加 logback 日志输出文件配置
#logging.file.name=app.log

spring.ai.dashscope.rerank.api-key=key
spring.ai.dashscope.api-key=key